version: '3.3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  app:
    build:
      context: ./app
    depends_on:
      - mysql
    ports:
      - "80:80"
    volumes:
      - ../code:/var/www/html
volumes:
  mysql_data:
